# -*- coding: utf-8 -*-
"""
Act III resume/repair runner (night-shift intervention, ~05:05).

Why this exists: the original run_suite3.py ran every case at lattice speed
u = 0.10, which sits too close to the LBM stability edge for deep-stall
violence -- two cases (a16_h10p90, a18_speck) blew up to NaN. This runner:

  * KEEPS every completed, NaN-free case CSV from the first pass (the six
    good 16-deg cases stay at u = 0.10),
  * RERUNS NaN victims and runs all remaining cases at u = 0.08 (25% more
    steps for the same physics, comfortably inside the stability margin),
  * appends to the same suite3.log and ends with the same 'act III complete'
    marker so the Act IV chain watcher keeps working unmodified.

Comparisons are made WITHIN each angle block against that block's own speck
baseline, so per-block lattice-speed consistency is what matters -- the 18
and 20 deg blocks will be uniformly u = 0.08.
"""
from __future__ import annotations

import csv as csv_mod
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ASSETS = HERE / "assets"
SUITE = HERE / "results" / "suite"
RUN_CFG = HERE / "tunnel_run.txt"
EXE = Path(r"L:\Dev\FluidX3D\bin\FluidX3D_headless.exe")
EXE_DIR = Path(r"L:\Dev\FluidX3D")

RE_STALL = 2.21e6
CHORD = 0.9022
T_END_SI = 0.5
VRAM_MB = 8000
U_SAFE = 0.08               # stability-margin lattice speed for rerun cases
ALPHAS = (16.0, 18.0, 20.0)

DESIGNS = [
    ("speck", "wing_speck_s0.25m.stl"),
    ("h10p50", "wing_vg_h10mm_p50mm_s0.25m.stl"),
    ("h10p90", "wing_vg_h10mm_p90mm_s0.25m.stl"),
    ("h12p50", "wing_vg_h12mm_p50mm_s0.25m.stl"),
    ("h12p90", "wing_vg_h12mm_p90mm_s0.25m.stl"),
    ("h16p50", "wing_vg_h16mm_p50mm_s0.25m.stl"),
    ("h16p90", "wing_vg_h16mm_p90mm_s0.25m.stl"),
]


def log(msg: str) -> None:
    line = f"[{time.strftime('%H:%M:%S')}] {msg}"
    print(line, flush=True)
    with open(SUITE / "suite3.log", "a", encoding="utf-8") as fh:
        fh.write(line + "\n")


def case_is_good(case_csv: Path) -> bool:
    """A keepable first-pass case: complete (>=50 samples) and NaN-free."""
    if not case_csv.exists():
        return False
    n, bad = 0, False
    with open(case_csv, encoding="utf-8") as fh:
        for ln in fh:
            if ln.startswith("#"):
                continue
            n += 1
            if "nan" in ln.lower():
                bad = True
    return n >= 50 and not bad


def write_config(stl: Path, aoa: float, case_csv: Path) -> None:
    RUN_CFG.write_text(
        "# auto-generated by run_suite3b.py (stability rerun, u=0.08)\n"
        f"mode        = slice\n"
        f"stl         = {stl.as_posix()}\n"
        f"aoa_deg     = {aoa}\n"
        f"re          = {RE_STALL:.4g}\n"
        f"vram_mb     = {VRAM_MB}\n"
        f"u           = {U_SAFE}\n"
        f"span_m      = 0.25\n"
        f"chord_m     = {CHORD}\n"
        f"t_end_si    = {T_END_SI}\n"
        f"video_s     = 0\n"
        f"log_every   = 2000\n"
        f"csv         = {case_csv.as_posix()}\n",
        encoding="utf-8")


def settled_stats(case_csv: Path):
    rows = []
    with open(case_csv, encoding="utf-8") as fh:
        for r in csv_mod.reader(ln for ln in fh if not ln.startswith("#")):
            if len(r) >= 6 and "nan" not in ",".join(r).lower():
                rows.append((float(r[0]), float(r[4]), float(r[5])))
    if len(rows) < 20:
        return None
    cut = rows[int(0.4 * len(rows)):]
    n = len(cut)
    cl = sum(r[2] for r in cut) / n
    cd = sum(r[1] for r in cut) / n
    pp = max(r[2] for r in cut) - min(r[2] for r in cut)
    half = n // 2
    drift = (sum(r[2] for r in cut[half:]) / max(1, n - half)
             - sum(r[2] for r in cut[:half]) / max(1, half))
    return cl, cd, pp, n, drift


def main() -> int:
    SUITE.mkdir(parents=True, exist_ok=True)
    stats = {}
    cases = [(f"a{aoa:.0f}_{d}", stl, aoa) for aoa in ALPHAS
             for (d, stl) in DESIGNS]
    for i, (label, stl_name, aoa) in enumerate(cases, start=1):
        case_csv = SUITE / f"act3_{label}.csv"
        if case_is_good(case_csv):
            stats[label] = settled_stats(case_csv)
            log(f"case {i}/{len(cases)}: {label} kept from first pass (u=0.10)")
            continue
        log(f"case {i}/{len(cases)}: {label} starting (u={U_SAFE})")
        write_config(ASSETS / stl_name, aoa, case_csv)
        t0 = time.time()
        with open(SUITE / f"act3_{label}.consolelog", "w", encoding="utf-8",
                  errors="replace") as con:
            proc = subprocess.run([str(EXE)], cwd=str(EXE_DIR),
                                  stdout=con, stderr=subprocess.STDOUT)
        mins = (time.time() - t0) / 60.0
        s = settled_stats(case_csv) if case_csv.exists() else None
        if s is None:
            log(f"case {label} FAILED (rc={proc.returncode}) after {mins:.1f} min")
            continue
        stats[label] = s
        log(f"case {label} done in {mins:.1f} min: Cl={s[0]:.4f} Cd={s[1]:.4f} "
            f"buffet={s[2]:.4f} drift={s[4]:+.4f}")

    lines = ["# Act III -- VG height x spacing matrix vs speck baseline", "",
             f"Slice mode headless, Re {RE_STALL:.3g} (80 mph), {T_END_SI} s physics.",
             "16-deg block at u=0.10 (first pass); 18/20-deg blocks and NaN",
             "reruns at u=0.08 (stability). Deltas are within-block, so the",
             "lattice-speed split does not contaminate any comparison.",
             "(!) = drifting settled mean, treat as provisional.", ""]
    for aoa in ALPHAS:
        base = stats.get(f"a{aoa:.0f}_speck")
        lines.append(f"## alpha = {aoa:.0f} deg")
        lines.append("")
        if not base:
            lines += ["speck baseline missing - no verdict at this angle", ""]
            continue
        lines += [f"speck baseline: Cl={base[0]:.4f} Cd={base[1]:.4f} "
                  f"buffet={base[2]:.4f} drift={base[4]:+.4f}", "",
                  "| design | mean Cl | dCl | dCl % | mean Cd | dCd | buffet | drift |",
                  "|---|---|---|---|---|---|---|---|"]
        for d, _stl in DESIGNS[1:]:
            s = stats.get(f"a{aoa:.0f}_{d}")
            if not s:
                lines.append(f"| {d} | (missing) | | | | | | |")
                continue
            flag = " (!)" if abs(s[4]) > 0.05 * abs(s[0]) else ""
            lines.append(f"| {d} | {s[0]:.4f} | {s[0]-base[0]:+.4f} | "
                         f"{(s[0]-base[0])/abs(base[0])*100.0:+.1f}% | "
                         f"{s[1]:.4f} | {s[1]-base[1]:+.4f} | {s[2]:.4f} | "
                         f"{s[4]:+.4f}{flag} |")
        lines.append("")
    out = SUITE / "REPORT_act3.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    log(f"act III complete -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
