# -*- coding: utf-8 -*-
"""
VG comparison suite runner for the FluidX3D tunnel.

Runs the owner's specified matrix sequentially on the GPU:

    {80 mph, 60 mph} x {clean, VG 8 mm, VG 12 mm, VG 16 mm}   at 14 deg AoA

in high-resolution slice mode (0.25 m span-periodic strip, ~1.6 mm cells, so
the vanes carry 5-10 lattice cells of real physics). Each case simulates a
fixed amount of PHYSICAL airflow time and auto-closes; forces stream to a
per-case CSV. After the last case the settled-window statistics become
results/suite/REPORT.md with clean-baseline deltas per speed.

Airspeed -> Reynolds at the measured 0.9022 m aileron chord (ISA sea level):
    80 mph = 35.76 m/s -> Re 2.21e6      60 mph = 26.82 m/s -> Re 1.66e6

Run:  python gpu/fluidx3d/run_suite.py          (takes the GPU for ~4-6 h)
Progress: tail gpu/fluidx3d/results/suite/suite.log
"""
from __future__ import annotations

import csv as csv_mod
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ASSETS = HERE / "assets"
SUITE = HERE / "results" / "suite"
RUN_CFG = HERE / "tunnel_run.txt"
EXE = Path(r"L:\Dev\FluidX3D\bin\FluidX3D.exe")
EXE_DIR = Path(r"L:\Dev\FluidX3D")

NU_AIR = 1.4607e-5          # ISA sea level kinematic viscosity, m^2/s
CHORD = 0.9022              # aileron-station chord, m [DXF measured]
AOA_DEG = 14.0              # near-stall test angle per the owner's matrix
T_END_SI = 0.5              # seconds of physical airflow per case (settle + average)
VRAM_MB = 8000              # per-case lattice budget (~1.6 mm cells in slice mode)

SPEEDS = [                  # (label, mph)
    ("80mph", 80.0),
    ("60mph", 60.0),
]
DESIGNS = [                 # (label, stl file)
    ("clean", "wing_a0_binary_s0.25m.stl"),
    ("vg08mm", "wing_vg_h8mm_s0.25m.stl"),
    ("vg12mm", "wing_vg_h12mm_s0.25m.stl"),
    ("vg16mm", "wing_vg_h16mm_s0.25m.stl"),
]


def log(msg: str) -> None:
    """Timestamped line to console and the suite log (monitor-friendly)."""
    line = f"[{time.strftime('%H:%M:%S')}] {msg}"
    print(line, flush=True)
    with open(SUITE / "suite.log", "a", encoding="utf-8") as fh:
        fh.write(line + "\n")


def write_config(stl: Path, re_value: float, case_csv: Path) -> None:
    """Per-case tunnel_run.txt -- the exe reads this fixed path at startup."""
    RUN_CFG.write_text(
        "# auto-generated by run_suite.py\n"
        f"mode        = slice\n"
        f"stl         = {stl.as_posix()}\n"
        f"aoa_deg     = {AOA_DEG}\n"
        f"re          = {re_value:.4g}\n"
        f"vram_mb     = {VRAM_MB}\n"
        f"u           = 0.10\n"
        f"span_m      = 0.25\n"
        f"chord_m     = {CHORD}\n"
        f"t_end_si    = {T_END_SI}\n"
        f"video_s     = 0\n"
        f"log_every   = 2000\n"
        f"csv         = {case_csv.as_posix()}\n",
        encoding="utf-8")


def settled_stats(case_csv: Path) -> tuple[float, float, float, int]:
    """(mean Cl, mean Cd, Cl peak-to-peak, n) over the last 60% of samples."""
    rows = []
    with open(case_csv, encoding="utf-8") as fh:
        for r in csv_mod.reader(ln for ln in fh if not ln.startswith("#")):
            if len(r) >= 6:
                rows.append((float(r[0]), float(r[4]), float(r[5])))
    cut = rows[int(0.4 * len(rows)):]               # drop the startup transient
    n = len(cut)
    cl = sum(r[2] for r in cut) / n
    cd = sum(r[1] for r in cut) / n
    pp = max(r[2] for r in cut) - min(r[2] for r in cut)
    return cl, cd, pp, n


def main() -> int:
    SUITE.mkdir(parents=True, exist_ok=True)
    results: dict[str, dict[str, tuple]] = {}
    total = len(SPEEDS) * len(DESIGNS)
    done = 0
    for sp_label, mph in SPEEDS:
        re_value = (mph * 0.44704) * CHORD / NU_AIR
        results[sp_label] = {}
        for d_label, stl_name in DESIGNS:
            done += 1
            stl = ASSETS / stl_name
            case_csv = SUITE / f"{sp_label}_{d_label}.csv"
            log(f"case {done}/{total}: {sp_label} {d_label} (Re={re_value:.3g}) starting")
            write_config(stl, re_value, case_csv)
            t0 = time.time()
            # The exe auto-closes after t_end_si seconds of physics (proven in
            # the smoke test), so a plain blocking call sequences the suite.
            # Console banner/output is captured per case so the solver's own
            # printout (resolution, mm/cell, dt, warnings) stays inspectable.
            with open(SUITE / f"{sp_label}_{d_label}.consolelog", "w",
                      encoding="utf-8", errors="replace") as con:
                proc = subprocess.run([str(EXE)], cwd=str(EXE_DIR),
                                      stdout=con, stderr=subprocess.STDOUT)
            mins = (time.time() - t0) / 60.0
            if proc.returncode != 0 or not case_csv.exists():
                log(f"case {sp_label} {d_label} FAILED (rc={proc.returncode}) after {mins:.1f} min")
                continue
            cl, cd, pp, n = settled_stats(case_csv)
            results[sp_label][d_label] = (cl, cd, pp, n)
            log(f"case {sp_label} {d_label} done in {mins:.1f} min: "
                f"Cl={cl:.4f} Cd={cd:.4f} buffet_pp={pp:.4f} ({n} samples)")

    # ---- report: clean-baseline deltas per speed ---------------------------
    lines = ["# VG comparison suite -- FluidX3D slice mode",
             "",
             f"14 deg AoA, {T_END_SI} s of physical airflow per case, "
             f"{VRAM_MB} MB lattice (~1.6 mm cells), 0.25 m span-periodic strip.",
             "Trust DELTAS vs the clean baseline, not absolute values "
             "(coarse-lattice LBM bias is shared by every case).", ""]
    for sp_label, _ in SPEEDS:
        block = results.get(sp_label, {})
        if "clean" not in block:
            lines += [f"## {sp_label}: clean baseline missing - no verdict", ""]
            continue
        cl0, cd0, pp0, _ = block["clean"]
        lines += [f"## {sp_label}", "",
                  "| design | mean Cl | dCl vs clean | mean Cd | dCd | buffet pk-pk |",
                  "|---|---|---|---|---|---|",
                  f"| clean | {cl0:.4f} | -- | {cd0:.4f} | -- | {pp0:.4f} |"]
        for d_label, _ in DESIGNS[1:]:
            if d_label not in block:
                lines.append(f"| {d_label} | FAILED | | | | |")
                continue
            cl, cd, pp, _ = block[d_label]
            lines.append(f"| {d_label} | {cl:.4f} | {cl - cl0:+.4f} "
                         f"({(cl - cl0) / max(1e-9, abs(cl0)) * 100.0:+.1f}%) | "
                         f"{cd:.4f} | {cd - cd0:+.4f} | {pp:.4f} |")
        lines.append("")
    report = SUITE / "REPORT.md"
    report.write_text("\n".join(lines), encoding="utf-8")
    log(f"suite complete -> {report}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
