# -*- coding: utf-8 -*-
"""
Act III overnight mega-suite (owner-designed matrix, 2026-06-12):

    Baselines:  speck wing (roll-artifact-broken clean reference)
                at alpha = 16, 18, 20 deg
    VG matrix:  heights {10, 12, 16 mm} x pair pitches {50, 90 mm}
                at alpha = 16, 18, 20 deg
    = 3 + 18 = 21 cases, all at Re 2.21e6 (80 mph full-flap stall speed).

Runs on the HEADLESS exe (no window, no rendering -- roughly doubles
throughput; the owner gets to sleep). The speck wing serves as baseline per
the owner's call: its broken-coherence flow is the honest reference, so
VG deltas are measured against physics rather than the chocolate-roll
artifact.

Outputs: act3_a{alpha}_{design}.csv (+ .consolelog) in results/suite/,
progress in suite3.log, final per-angle delta tables in REPORT_act3.md.

Run:  python gpu/fluidx3d/run_suite3.py      (~6-7 h on the 5090)
"""
from __future__ import annotations

import csv as csv_mod
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ASSETS = HERE / "assets"
SUITE = HERE / "results" / "suite"
RUN_CFG = HERE / "tunnel_run.txt"
EXE = Path(r"L:\Dev\FluidX3D\bin\FluidX3D_headless.exe")   # no window, no rendering
EXE_DIR = Path(r"L:\Dev\FluidX3D")

RE_STALL = 2.21e6
CHORD = 0.9022
T_END_SI = 0.5
VRAM_MB = 8000
ALPHAS = (16.0, 18.0, 20.0)

DESIGNS = [          # (label, stl) -- speck first: it is the baseline article
    ("speck", "wing_speck_s0.25m.stl"),
    ("h10p50", "wing_vg_h10mm_p50mm_s0.25m.stl"),
    ("h10p90", "wing_vg_h10mm_p90mm_s0.25m.stl"),
    ("h12p50", "wing_vg_h12mm_p50mm_s0.25m.stl"),
    ("h12p90", "wing_vg_h12mm_p90mm_s0.25m.stl"),
    ("h16p50", "wing_vg_h16mm_p50mm_s0.25m.stl"),
    ("h16p90", "wing_vg_h16mm_p90mm_s0.25m.stl"),
]


def log(msg: str) -> None:
    line = f"[{time.strftime('%H:%M:%S')}] {msg}"
    print(line, flush=True)
    with open(SUITE / "suite3.log", "a", encoding="utf-8") as fh:
        fh.write(line + "\n")


def write_config(stl: Path, aoa: float, case_csv: Path) -> None:
    RUN_CFG.write_text(
        "# auto-generated by run_suite3.py\n"
        f"mode        = slice\n"
        f"stl         = {stl.as_posix()}\n"
        f"aoa_deg     = {aoa}\n"
        f"re          = {RE_STALL:.4g}\n"
        f"vram_mb     = {VRAM_MB}\n"
        f"u           = 0.075\n"  # was 0.10: two lattice blowups at 16-18 deg
                                  # (a16_h10p90, a18_speck) triggered the
                                  # stability fallback -- smaller lattice speed
                                  # buys margin at ~1.33x steps per physics-second
        f"span_m      = 0.25\n"
        f"chord_m     = {CHORD}\n"
        f"t_end_si    = {T_END_SI}\n"
        f"video_s     = 0\n"
        f"log_every   = 2000\n"
        f"csv         = {case_csv.as_posix()}\n",
        encoding="utf-8")


def settled_stats(case_csv: Path):
    """(mean Cl, mean Cd, Cl pk-pk, n, drift) -- same contract as analyze_suite."""
    rows = []
    with open(case_csv, encoding="utf-8") as fh:
        for r in csv_mod.reader(ln for ln in fh if not ln.startswith("#")):
            if len(r) >= 6:
                rows.append((float(r[0]), float(r[4]), float(r[5])))
    if len(rows) < 20:
        return None
    cut = rows[int(0.4 * len(rows)):]
    n = len(cut)
    cl = sum(r[2] for r in cut) / n
    cd = sum(r[1] for r in cut) / n
    pp = max(r[2] for r in cut) - min(r[2] for r in cut)
    half = n // 2
    cl_a = sum(r[2] for r in cut[:half]) / max(1, half)
    cl_b = sum(r[2] for r in cut[half:]) / max(1, n - half)
    return cl, cd, pp, n, cl_b - cl_a


def main() -> int:
    SUITE.mkdir(parents=True, exist_ok=True)
    stats = {}
    cases = [(f"a{aoa:.0f}_{d_label}", stl, aoa)
             for aoa in ALPHAS for (d_label, stl) in DESIGNS]
    for i, (label, stl_name, aoa) in enumerate(cases, start=1):
        case_csv = SUITE / f"act3_{label}.csv"
        # Resume logic (added after the 04:57 restart): a case whose CSV
        # already yields valid, non-NaN settled stats is banked -- skip it.
        # NaN victims fail the self-equality test and rerun automatically.
        s_pre = settled_stats(case_csv) if case_csv.exists() else None
        if s_pre is not None and s_pre[0] == s_pre[0]:
            stats[label] = s_pre
            log(f"case {i}/{len(cases)}: {label} already banked, skipping")
            continue
        log(f"case {i}/{len(cases)}: {label} starting")
        write_config(ASSETS / stl_name, aoa, case_csv)
        t0 = time.time()
        with open(SUITE / f"act3_{label}.consolelog", "w", encoding="utf-8",
                  errors="replace") as con:
            proc = subprocess.run([str(EXE)], cwd=str(EXE_DIR),
                                  stdout=con, stderr=subprocess.STDOUT)
        mins = (time.time() - t0) / 60.0
        s = settled_stats(case_csv) if case_csv.exists() else None
        if s is None:
            log(f"case {label} FAILED (rc={proc.returncode}) after {mins:.1f} min")
            continue
        stats[label] = s
        log(f"case {label} done in {mins:.1f} min: Cl={s[0]:.4f} Cd={s[1]:.4f} "
            f"buffet={s[2]:.4f} drift={s[4]:+.4f}")

    # ---- per-angle report against the speck baseline ----------------------
    lines = ["# Act III -- VG height x spacing matrix vs speck baseline", "",
             f"Slice mode headless, Re {RE_STALL:.3g} (80 mph), {T_END_SI} s "
             "physics per case, settled-window stats, (!) = drifting mean.",
             "Speck wing = coherence-broken clean reference (owner's control).", ""]
    for aoa in ALPHAS:
        base = stats.get(f"a{aoa:.0f}_speck")
        lines.append(f"## alpha = {aoa:.0f} deg")
        lines.append("")
        if base is None:
            lines += ["speck baseline missing - no verdict at this angle", ""]
            continue
        lines += [f"speck baseline: Cl={base[0]:.4f} Cd={base[1]:.4f} "
                  f"buffet={base[2]:.4f} drift={base[4]:+.4f}", "",
                  "| design | mean Cl | dCl | dCl % | mean Cd | dCd | buffet | drift |",
                  "|---|---|---|---|---|---|---|---|"]
        for d_label, _ in DESIGNS[1:]:
            s = stats.get(f"a{aoa:.0f}_{d_label}")
            if s is None:
                lines.append(f"| {d_label} | (missing) | | | | | | |")
                continue
            flag = " (!)" if abs(s[4]) > 0.05 * abs(s[0]) else ""
            lines.append(f"| {d_label} | {s[0]:.4f} | {s[0]-base[0]:+.4f} | "
                         f"{(s[0]-base[0])/abs(base[0])*100.0:+.1f}% | "
                         f"{s[1]:.4f} | {s[1]-base[1]:+.4f} | {s[2]:.4f} | "
                         f"{s[4]:+.4f}{flag} |")
        lines.append("")
    out = SUITE / "REPORT_act3.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    log(f"act III complete -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
