# -*- coding: utf-8 -*-
"""
Act II suite: ride-the-stall comparison at stall airspeed, plus the
roll-artifact control case (owner-designed matrix, 2026-06-12 early am).

Cases (all Re 2.21e6 = 80 mph full-flap stall speed at the 0.9022 m chord):

    alpha 16 deg (riding the stall):   clean | VG 12 mm | VG 16 mm
    alpha 18 deg (past clean stall):   clean | VG 12 mm | VG 16 mm
    alpha 14 deg speck control:        clean wing + 8 mm mid-span speck
        -> compared against Act I's 80mph_clean.csv (same angle/Re), this
           measures how much of the clean baseline's lift is the artificial
           spanwise-roller artifact rather than honest aerodynamics.

Outputs per case: act2_a{alpha}_{design}.csv (+ .consolelog) in results/suite/.
Ends by writing REPORT_act2.md with per-angle clean-baseline deltas.

Run:  python gpu/fluidx3d/run_suite2.py     (takes the GPU for ~2.5 h)
"""
from __future__ import annotations

import csv as csv_mod
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ASSETS = HERE / "assets"
SUITE = HERE / "results" / "suite"
RUN_CFG = HERE / "tunnel_run.txt"
EXE = Path(r"L:\Dev\FluidX3D\bin\FluidX3D.exe")
EXE_DIR = Path(r"L:\Dev\FluidX3D")

RE_STALL = 2.21e6           # 80 mph at the 0.9022 m aileron chord, ISA SL
CHORD = 0.9022
T_END_SI = 0.5
VRAM_MB = 8000

# (case label, STL file, alpha_deg)
# Speck control runs FIRST (owner wants to watch the rollers break live);
# its baseline is Act I's 80mph_clean.csv, so order is scientifically moot.
CASES = [
    ("a14_speck",  "wing_speck_s0.25m.stl",     14.0),   # roll-artifact control
    ("a16_clean",  "wing_a0_binary_s0.25m.stl", 16.0),
    ("a16_vg12mm", "wing_vg_h12mm_s0.25m.stl",  16.0),
    ("a16_vg16mm", "wing_vg_h16mm_s0.25m.stl",  16.0),
    ("a18_clean",  "wing_a0_binary_s0.25m.stl", 18.0),
    ("a18_vg12mm", "wing_vg_h12mm_s0.25m.stl",  18.0),
    ("a18_vg16mm", "wing_vg_h16mm_s0.25m.stl",  18.0),
]


def log(msg: str) -> None:
    line = f"[{time.strftime('%H:%M:%S')}] {msg}"
    print(line, flush=True)
    with open(SUITE / "suite2.log", "a", encoding="utf-8") as fh:
        fh.write(line + "\n")


def write_config(stl: Path, aoa: float, case_csv: Path) -> None:
    RUN_CFG.write_text(
        "# auto-generated by run_suite2.py\n"
        f"mode        = slice\n"
        f"stl         = {stl.as_posix()}\n"
        f"aoa_deg     = {aoa}\n"
        f"re          = {RE_STALL:.4g}\n"
        f"vram_mb     = {VRAM_MB}\n"
        f"u           = 0.10\n"
        f"span_m      = 0.25\n"
        f"chord_m     = {CHORD}\n"
        f"t_end_si    = {T_END_SI}\n"
        f"video_s     = 0\n"
        f"log_every   = 2000\n"
        f"csv         = {case_csv.as_posix()}\n",
        encoding="utf-8")


def settled_stats(case_csv: Path):
    rows = []
    with open(case_csv, encoding="utf-8") as fh:
        for r in csv_mod.reader(ln for ln in fh if not ln.startswith("#")):
            if len(r) >= 6:
                rows.append((float(r[0]), float(r[4]), float(r[5])))
    if len(rows) < 20:
        return None
    cut = rows[int(0.4 * len(rows)):]
    n = len(cut)
    return (sum(r[2] for r in cut) / n, sum(r[1] for r in cut) / n,
            max(r[2] for r in cut) - min(r[2] for r in cut), n)


def main() -> int:
    SUITE.mkdir(parents=True, exist_ok=True)
    stats = {}
    for i, (label, stl_name, aoa) in enumerate(CASES, start=1):
        case_csv = SUITE / f"act2_{label}.csv"
        log(f"case {i}/{len(CASES)}: {label} (aoa={aoa}, Re={RE_STALL:.3g}) starting")
        write_config(ASSETS / stl_name, aoa, case_csv)
        t0 = time.time()
        with open(SUITE / f"act2_{label}.consolelog", "w", encoding="utf-8",
                  errors="replace") as con:
            proc = subprocess.run([str(EXE)], cwd=str(EXE_DIR),
                                  stdout=con, stderr=subprocess.STDOUT)
        mins = (time.time() - t0) / 60.0
        s = settled_stats(case_csv) if case_csv.exists() else None
        if s is None:
            log(f"case {label} FAILED (rc={proc.returncode}) after {mins:.1f} min")
            continue
        stats[label] = s
        log(f"case {label} done in {mins:.1f} min: Cl={s[0]:.4f} Cd={s[1]:.4f} "
            f"buffet_pp={s[2]:.4f} ({s[3]} samples)")

    # ---- per-angle deltas + the artifact-control comparison ----------------
    lines = ["# Act II -- ride-the-stall suite (Re 2.21e6, stall airspeed)", "",
             "Slice mode, settled-window averages; trust deltas.", ""]
    for aoa, prefix in ((16.0, "a16"), (18.0, "a18")):
        base = stats.get(f"{prefix}_clean")
        lines.append(f"## alpha = {aoa:.0f} deg")
        lines.append("")
        if base is None:
            lines += ["clean baseline missing - no verdict", ""]
            continue
        lines += ["| design | mean Cl | dCl | dCl % | mean Cd | dCd | buffet |",
                  "|---|---|---|---|---|---|---|",
                  f"| clean | {base[0]:.4f} | -- | -- | {base[1]:.4f} | -- | {base[2]:.4f} |"]
        for d in ("vg12mm", "vg16mm"):
            s = stats.get(f"{prefix}_{d}")
            if s is None:
                lines.append(f"| {d} | (missing) | | | | | |")
                continue
            lines.append(f"| {d} | {s[0]:.4f} | {s[0]-base[0]:+.4f} | "
                         f"{(s[0]-base[0])/abs(base[0])*100.0:+.1f}% | "
                         f"{s[1]:.4f} | {s[1]-base[1]:+.4f} | {s[2]:.4f} |")
        lines.append("")
    # Artifact control: speck @14 vs Act I clean @14 (same angle, same Re).
    speck = stats.get("a14_speck")
    act1_clean = SUITE / "80mph_clean.csv"
    if speck and act1_clean.exists():
        base = settled_stats(act1_clean)
        if base:
            lines += ["## roll-artifact control (14 deg)",
                      "",
                      f"clean (Act I): Cl={base[0]:.4f}  |  clean+speck: Cl={speck[0]:.4f}"
                      f"  ->  coherence artifact ~ {base[0]-speck[0]:+.4f} Cl "
                      f"({(base[0]-speck[0])/abs(base[0])*100.0:+.1f}% of the clean baseline)",
                      "",
                      "Interpretation: lift attributable to artificially coherent",
                      "spanwise rollers in the periodic slice. Subtract mentally from",
                      "every clean-vs-VG delta at this angle.", ""]
    out = SUITE / "REPORT_act2.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    log(f"act II complete -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
