# -*- coding: utf-8 -*-
"""
Generic test-block runner for the FluidX3D tunnel: one AoA x one speed x a
list of designs, sequential, slice mode, force CSVs named so analyze_suite
and ad-hoc readers can find them.

Built for the 18-degree pivot experiment (does the clean wing finally
collapse while a VG'd wing holds on?) but fully general:

    python gpu/fluidx3d/run_block.py --aoa 18 --mph 80 --designs clean,vg12mm,vg16mm

CSVs land in results/suite/ as  a{AOA}_{MPH}mph_{design}.csv  (the overnight
suite's own files keep their original names; nothing is overwritten).
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Reuse the proven pieces of the overnight runner rather than re-implementing:
# config writer contract, stats, and the asset/exe paths all stay identical.
sys.path.insert(0, str(HERE))
from run_suite import (ASSETS, CHORD, EXE, EXE_DIR, NU_AIR, RUN_CFG, SUITE,
                       T_END_SI, VRAM_MB, settled_stats)

STL_BY_DESIGN = {
    "clean":  "wing_a0_binary_s0.25m.stl",
    "vg08mm": "wing_vg_h8mm_s0.25m.stl",
    "vg12mm": "wing_vg_h12mm_s0.25m.stl",
    "vg16mm": "wing_vg_h16mm_s0.25m.stl",
    "speck":  "wing_speck_s0.25m.stl",   # clean + one 4 mm bump: quasi-2D artifact meter
    # Aileron-effectiveness articles (two disjoint shells each: main+aileron,
    # 1/16 in gap open; n = neutral, d15/u15 = 15 deg down/up):
    "cl_n":   "wing_clean_ail_n_s0.25m.stl",
    "cl_d15": "wing_clean_ail_d15_s0.25m.stl",
    "cl_u15": "wing_clean_ail_u15_s0.25m.stl",
    "vg_n":   "wing_vg16p50_ail_n_s0.25m.stl",
    "vg_d15": "wing_vg16p50_ail_d15_s0.25m.stl",
    "vg_u15": "wing_vg16p50_ail_u15_s0.25m.stl",
}


def log(msg: str) -> None:
    line = f"[{time.strftime('%H:%M:%S')}] {msg}"
    print(line, flush=True)
    with open(SUITE / "suite.log", "a", encoding="utf-8") as fh:
        fh.write(line + "\n")


def write_config(stl: Path, aoa: float, re_value: float, case_csv: Path,
                 vram_mb: float = float(VRAM_MB), u: float = 0.075,
                 span_m: float = 0.25) -> None:
    RUN_CFG.write_text(
        "# auto-generated by run_block.py\n"
        f"mode        = slice\n"
        f"stl         = {stl.as_posix()}\n"
        f"aoa_deg     = {aoa}\n"
        f"re          = {re_value:.4g}\n"
        f"vram_mb     = {vram_mb:g}\n"
        f"u           = {u:g}\n"
        f"span_m      = {span_m:g}\n"
        f"chord_m     = {CHORD}\n"
        f"t_end_si    = {T_END_SI}\n"
        f"video_s     = 0\n"
        f"log_every   = 2000\n"
        f"csv         = {case_csv.as_posix()}\n",
        encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="single test block runner")
    ap.add_argument("--aoa", type=float, required=True)
    ap.add_argument("--mph", type=float, default=80.0)
    ap.add_argument("--designs", default="clean,vg12mm,vg16mm",
                    help="comma list from: " + ",".join(STL_BY_DESIGN))
    ap.add_argument("--vram", type=float, default=12000.0,
                    help="lattice VRAM budget MB (default 12000 per owner "
                         "standard; 2500 = ~2.6 mm coarse screening)")
    ap.add_argument("--u", type=float, default=0.075,
                    help="lattice speed (0.075 = the stability protocol "
                         "for alpha >= 16; raise to 0.10 only at low alpha)")
    ap.add_argument("--span", type=float, default=0.25,
                    help="STL true span in m; 1.5 with the full wing = the "
                         "WIDE ARENA (1.66 chords, room for real 3D stall "
                         "cells the 0.25 m slice suppressed)")
    a = ap.parse_args()

    SUITE.mkdir(parents=True, exist_ok=True)
    re_value = (a.mph * 0.44704) * CHORD / NU_AIR
    designs = [d.strip() for d in a.designs.split(",") if d.strip()]
    results = {}
    for i, d in enumerate(designs, 1):
        stl = ASSETS / STL_BY_DESIGN[d]
        case_csv = SUITE / f"a{a.aoa:g}_{a.mph:g}mph_{d}.csv"
        log(f"block case {i}/{len(designs)}: aoa={a.aoa:g} {a.mph:g}mph {d} "
            f"(Re={re_value:.3g}, span={a.span:g} m, vram={a.vram:g}) starting")
        write_config(stl, a.aoa, re_value, case_csv,
                     vram_mb=a.vram, u=a.u, span_m=a.span)
        t0 = time.time()
        with open(SUITE / f"a{a.aoa:g}_{a.mph:g}mph_{d}.consolelog", "w",
                  encoding="utf-8", errors="replace") as con:
            proc = subprocess.run([str(EXE)], cwd=str(EXE_DIR),
                                  stdout=con, stderr=subprocess.STDOUT)
        mins = (time.time() - t0) / 60.0
        stats = settled_stats(case_csv) if case_csv.exists() else None
        if stats is None:
            log(f"block case {d} FAILED (rc={proc.returncode}) after {mins:.1f} min")
            continue
        cl, cd, pp, n = stats
        results[d] = (cl, cd, pp)
        log(f"block case {d} done in {mins:.1f} min: Cl={cl:.4f} Cd={cd:.4f} "
            f"buffet={pp:.4f} ({n} samples)")

    # Compact verdict straight into the log (full tables stay analyze_suite's job).
    if "clean" in results:
        cl0 = results["clean"][0]
        for d, (cl, cd, pp) in results.items():
            if d != "clean":
                log(f"block verdict aoa={a.aoa:g}: {d} dCl={cl - cl0:+.4f} "
                    f"({(cl - cl0) / abs(cl0) * 100.0:+.1f}%) vs clean")
    log(f"block complete: aoa={a.aoa:g} {a.mph:g}mph [{', '.join(designs)}]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
