# -*- coding: utf-8 -*-
"""
Act IV conditional follow-on (owner's pre-sleep order): two speed blocks,
all 7 articles (speck baseline + 6 VG designs), launched automatically by
chain_suite4.py if Act III completes before 09:30.

  Block A -- cruise drag tax:   200 mph (Re 5.52e6) at alpha = 2 deg.
      The angle where the airplane actually spends fast flight; measures
      what each VG row costs in Cd when nothing needs fixing. Attached
      steady flow settles fast, so a shorter physics window suffices.
  Block B -- deep flare:        60 mph (Re 1.66e6) at alpha = 18 deg.
      Below book stall speed at high angle: the regime of the owner's
      gust/flare/takeoff concern.

Outputs: act4_{label}.csv + .consolelog, suite4.log, REPORT_act4.md.
"""
from __future__ import annotations

import csv as csv_mod
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ASSETS = HERE / "assets"
SUITE = HERE / "results" / "suite"
RUN_CFG = HERE / "tunnel_run.txt"
EXE = Path(r"L:\Dev\FluidX3D\bin\FluidX3D_headless.exe")
EXE_DIR = Path(r"L:\Dev\FluidX3D")

CHORD = 0.9022
VRAM_MB = 8000

DESIGNS = [
    ("speck", "wing_speck_s0.25m.stl"),
    ("h10p50", "wing_vg_h10mm_p50mm_s0.25m.stl"),
    ("h10p90", "wing_vg_h10mm_p90mm_s0.25m.stl"),
    ("h12p50", "wing_vg_h12mm_p50mm_s0.25m.stl"),
    ("h12p90", "wing_vg_h12mm_p90mm_s0.25m.stl"),
    ("h16p50", "wing_vg_h16mm_p50mm_s0.25m.stl"),
    ("h16p90", "wing_vg_h16mm_p90mm_s0.25m.stl"),
]
# (block tag, Re, alpha_deg, t_end_si, description)
BLOCKS = [
    ("cruise200", 5.52e6, 2.0, 0.25, "200 mph cruise drag tax"),
    ("flare60",   1.66e6, 18.0, 0.5, "60 mph deep flare"),
]


def log(msg: str) -> None:
    line = f"[{time.strftime('%H:%M:%S')}] {msg}"
    print(line, flush=True)
    with open(SUITE / "suite4.log", "a", encoding="utf-8") as fh:
        fh.write(line + "\n")


def write_config(stl: Path, aoa: float, re_value: float, t_end: float,
                 case_csv: Path) -> None:
    RUN_CFG.write_text(
        "# auto-generated by run_suite4.py\n"
        f"mode        = slice\n"
        f"stl         = {stl.as_posix()}\n"
        f"aoa_deg     = {aoa}\n"
        f"re          = {re_value:.4g}\n"
        f"vram_mb     = {VRAM_MB}\n"
        f"u           = 0.10\n"
        f"span_m      = 0.25\n"
        f"chord_m     = {CHORD}\n"
        f"t_end_si    = {t_end}\n"
        f"video_s     = 0\n"
        f"log_every   = 2000\n"
        f"csv         = {case_csv.as_posix()}\n",
        encoding="utf-8")


def settled_stats(case_csv: Path):
    rows = []
    with open(case_csv, encoding="utf-8") as fh:
        for r in csv_mod.reader(ln for ln in fh if not ln.startswith("#")):
            if len(r) >= 6:
                rows.append((float(r[0]), float(r[4]), float(r[5])))
    if len(rows) < 15:
        return None
    cut = rows[int(0.4 * len(rows)):]
    n = len(cut)
    cl = sum(r[2] for r in cut) / n
    cd = sum(r[1] for r in cut) / n
    pp = max(r[2] for r in cut) - min(r[2] for r in cut)
    half = n // 2
    drift = (sum(r[2] for r in cut[half:]) / max(1, n - half)
             - sum(r[2] for r in cut[:half]) / max(1, half))
    return cl, cd, pp, n, drift


def main() -> int:
    SUITE.mkdir(parents=True, exist_ok=True)
    stats = {}
    cases = [(f"{tag}_{d}", stl, re_v, aoa, t_end)
             for (tag, re_v, aoa, t_end, _) in BLOCKS
             for (d, stl) in DESIGNS]
    for i, (label, stl_name, re_v, aoa, t_end) in enumerate(cases, start=1):
        case_csv = SUITE / f"act4_{label}.csv"
        log(f"case {i}/{len(cases)}: {label} starting")
        write_config(ASSETS / stl_name, aoa, re_v, t_end, case_csv)
        t0 = time.time()
        with open(SUITE / f"act4_{label}.consolelog", "w", encoding="utf-8",
                  errors="replace") as con:
            proc = subprocess.run([str(EXE)], cwd=str(EXE_DIR),
                                  stdout=con, stderr=subprocess.STDOUT)
        mins = (time.time() - t0) / 60.0
        s = settled_stats(case_csv) if case_csv.exists() else None
        if s is None:
            log(f"case {label} FAILED (rc={proc.returncode}) after {mins:.1f} min")
            continue
        stats[label] = s
        log(f"case {label} done in {mins:.1f} min: Cl={s[0]:.4f} Cd={s[1]:.4f} "
            f"buffet={s[2]:.4f} drift={s[4]:+.4f}")

    lines = ["# Act IV -- cruise drag tax + deep flare blocks", "",
             "Slice mode headless; deltas vs the speck baseline per block;",
             "(!) = drifting mean, treat as provisional.", ""]
    for tag, re_v, aoa, _, desc in BLOCKS:
        base = stats.get(f"{tag}_speck")
        lines.append(f"## {desc} (Re {re_v:.3g}, alpha {aoa:.0f} deg)")
        lines.append("")
        if base is None:
            lines += ["speck baseline missing - no verdict", ""]
            continue
        lines += [f"speck baseline: Cl={base[0]:.4f} Cd={base[1]:.4f}", "",
                  "| design | mean Cl | dCl | mean Cd | dCd | dCd % | buffet | drift |",
                  "|---|---|---|---|---|---|---|---|"]
        for d, _stl in DESIGNS[1:]:
            s = stats.get(f"{tag}_{d}")
            if s is None:
                lines.append(f"| {d} | (missing) | | | | | | |")
                continue
            flag = " (!)" if abs(s[4]) > 0.05 * max(0.05, abs(s[0])) else ""
            lines.append(f"| {d} | {s[0]:.4f} | {s[0]-base[0]:+.4f} | "
                         f"{s[1]:.4f} | {s[1]-base[1]:+.4f} | "
                         f"{(s[1]-base[1])/abs(base[1])*100.0:+.1f}% | "
                         f"{s[2]:.4f} | {s[4]:+.4f}{flag} |")
        lines.append("")
    out = SUITE / "REPORT_act4.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    log(f"act IV complete -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
